### PR TITLE
Makes the  script work for the whole site

### PR DESCRIPTION
**Pull request by gbear605**
Makes the script work for the whole site.  It should work on the beta site as well.

### CODE REVIEW

**Comment by hyperobject** [comment]
There seems to be some kind of merge conflict with the pull request. Do you know how to fix that?

**Comment by gbear605** [comment]
Hmmm...  Github keeps being weird for me.  Think you could make me an editor on this project?  It would make it much simpler.  Anyway, no, I have absolutely no idea how to fix it.

**Comment by hyperobject** [comment]
Done! Also, the beta forums seem to use a different wrapper for the content
than the 1.4 site, so that might be something we should look into.

**Comment by gbear605** [comment]
Well, this seems to have bugs, so I'm going to close it.  Thanks for the fast response to the editing perms, BTW.

**Comment by hyperobject** [comment]
No problem.

**Pull request closed without merging**
